### ISSUE TITLE
make it for firefox/waterfox

### ISSUE THREAD

**Issue by ikkqqstudio** [KlibrDM/metro-tab#5]
make it for firefox/waterfox
Firefox/waterfox version of Chrome web store: https://addons.mozilla.org/en-US/firefox/

**Comment by ikkqqstudio** [comment]
it's had been 4 days and it gonna released on Firefox/waterfox version of Chrome web store soon?

**Comment by KlibrDM** [comment]
Waiting for review on Firefox add-on hub, I will close this issue once the extension is published.

**Comment by KlibrDM** [comment]
@ikkqqstudio the extension is now available on Firefox at the following link: https://addons.mozilla.org/en-US/firefox/addon/metro-speed-dial-new-tab-page/

The top-left `QuickNav` buttons are Chrome specific and were taken out for the Firefox version.

If you run into any issues please let me know.

**Comment by ikkqqstudio** [comment]
it worked on waterfox browser
but why Searchbox does opens Google instead of Duckduckgo and other search engine? i really wanted to Private searching
