### ISSUE TITLE
make able to Switch search engine

### ISSUE THREAD

**Issue by ikkqqstudio** [KlibrDM/metro-tab#6]
can you make it able to Switch Google to other search engine on metro-tab?
Search engines such as
Bing
Duckduckgo
startpage 
yahoo!
Yandex
Ecosia
Maybe custom

**Comment by KlibrDM** [comment]
Good idea, I'll look into it when I have some time, but this won't be high priority.

**Comment by ikkqqstudio** [comment]
okay i i'm waiting for it

**Comment by KlibrDM** [comment]
I have updated the gh-pages build with the search engine changes.

You can choose from a list of search engines from Settings -> Search Engines tab.

Please try it out here: https://klibrdm.github.io/metro-tab/ and let me know if everything is alright.

Once I get a confirmation from you I will create the builds for Chrome Web Store and Firefox Browser Add-ons. Those will take a few days to get published.

**Comment by KlibrDM** [comment]
Implemented & Published
